### ISSUE TITLE
set value?

### ISSUE THREAD

**Issue by pipiscrew** [rmanivannan/speedometer-jquery-plugin#1]
how I can set the value from code, currently I made this modification :

``` javascript
{
.
.
  this.changePosition = function (speedvalue){   
.
.
.
}
  return this;
 // $(this).bind(this.defaultProperty.eventListenerType,this.changePosition);
}
```

at html

``` javascript
    var y = $("#speedometer").myfunc({divFact:20,maxVal:400});
    y.changePosition(200);
```

``` html
<div id="speedometer"></div>
```

please advise!

**Comment by rmanivannan** [comment]
Apologize for the delayed response,

Appreciate for bring this up. 

Solution:
if you have not modified your "eventListenerType", you can update the input field value and trigger the "change event", else update the input value and trigger the corresponding event mapped to input field.

$('#speedometer').val(100).change()

many thanks,
Mani
+91 8867265278

**Comment by Hashane** [comment]
please help me to set the value from taken from database directly without using input field .please

**Comment by choxx** [comment]
@Hashane I don't know which scripting language you are using. I'm giving solution for PHP.
You can retrieve the value from database(based on which technique you are using to retrieve data) first and store into a PHP variable lets say `$value`.
Call your javascript function after page load and declare a variable in it, say `valueFromDB` & assign that `$value` to it as below:
`var valueFromDB = parseInt(" <?php echo $value; ");`

Now you have value from database in `valueFromDB`. You can call function with this value which will set the respective value from db in your speedometer.
Example:
`$('#speedometer').val(valueFromDB).change()`

**Comment by Hashane** [comment]
Thank you so much bro .Yes I was using PHP for that. As you got kind of
late to reply had to move on to another speedometer. Thank you so much
anyway. I'll re-add this speedometer to my project.Thank you so much again

**Comment by rmanivannan** [comment]
@Hashane, if you don't want to show input field use CSS to hide input field
