### ISSUE TITLE
Some text aligning issues + annoying comma removal

### ISSUE THREAD

**Issue by Rchik** [rmanivannan/speedometer-jquery-plugin#2]
If you take a look at your demo in Chrome (not sure about other browsers), you will see comma in top left corner of your speedometer, which can be removed by replacing speedNode init with join with the following: `var speedNobe = '<div class="speedNobe"><div></div></div><div class="speedPosition"></div>';`
Another issue is improper text alignment. As you may have noticed, you count number's top and left coordinates as induCatorNumbPosLeft and induCatorNumbPosTop, in reverse, that means you should reverse numbH/2 and numbW/2, cause they should be subtracted from the actual coordinates:

```
induCatorNumbPosLeft = (this.defaultProperty.edgeRadius - induCatorNumbPosX) - (this.defaultProperty.numbH/2);
induCatorNumbPosTop  = (this.defaultProperty.edgeRadius - induCatorNumbPosY) - (this.defaultProperty.numbW/2);
tempDiv += '<div class="numb '+dangCls+'" style="text-align: center;left:'+ induCatorNumbPosTop +'px;top:'+induCatorNumbPosLeft+'px;">'+ curIndVal +'</div>';
```

Notice  "text-align: center", that was added to place text exactly in the middle of the div.

The changes I offer to make produce a huge difference when you have options like {divFact:500, maxVal:6000, dangerLevel: 4000, numbW: 40, numbH: 18, indicatorNumbRadius:80}

**Comment by rmanivannan** [comment]
@Rchik Thanks a lot for sharing your findings and fix, You could have raised merge request with your changes.
