### ISSUE TITLE
Set starting value?

### ISSUE THREAD

**Issue by domantasg** [rmanivannan/speedometer-jquery-plugin#5]
Hey,
Awesome script! 

Once question though. Is it possible to set a starting value for speedometer. I have value in my input after page load but need to change it to make the speedometer update.

**Comment by hugotown** [comment]
maybe you can add another function like "setPosition" at the bottom of the script.

https://github.com/rmanivannan/speedometer-jquery-plugin/blob/master/speedometer-reusable/js/speedometer.js

**Comment by rmanivannan** [comment]
Thanks @hugotown  for your suggestion, have added method-'setPosition'.

Thanks @domantasg for your feedback and highlighting this enhancement
